spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        id:
          new_generator_mappings: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
    database: postgresql
  flyway:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    user: postgres
    password: postgres
    enabled: true
server:
  port: 8080
  servlet:
    context-path: /rest
custom:
  env: 'dev'
  test: true
  support-mail: 'support@email.com'
  swagger-url: 'localhost:8080'
  server-url: 'http://bojantrans.store.com/rest'
  frontend-url: 'http://bojantrans.store.com'
  website: 'https://bojantrans.store.com'
  jwt-signing-key: 'gnZbuW8ctpTWaebRmReAky4TLs4h7YTBYPeJGf5FTpSEuHZ8buxYpV7HPp9EE778GfqKRRTNcYn2jQbdVBzcavvFX3B47gteLDLvM7tmGKSH7Q4WsbKNX9zHMSbKqqJDfYkzqysymy6ftP7TZy2Yj8KwD5sseQM4Q3wyxGCENFbTzr5PRMKqfC6sDckB8sNDnxRpfY3JbmSTC2XM77sVqaapCVhWjD4cthhaAj8KuKGAC2tN5NgtAdUqWMLGY8Ns'
  jwt-validity: 180
  jwt-audience: 'lvh.me'
  salt: '$2a$10$XeMQWfXrTEzrlWg6d2Vm3u'
  digital-ocean:
    access-key: 'a'
    secret-key: 'b'
    bucket: 'bojantransstore-dev'
    region: 'fra1'
    url: 'bojantransstorespaces.com'


